doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        unix_socket: /var/lib/mysql/mysql.sock
        server_version: '8.0'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Backend\Products\Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Backend/Products/Infrastructure/Persistence/Mapping'
                prefix: 'App\Backend\Products\Domain'
                alias: Product
            App\Backend\Cart\Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Backend/Cart/Infrastructure/Persistence/Mapping'
                prefix: 'App\Backend\Cart\Domain'
                alias: Cart