doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            App\Backend\Products\Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%\src\Backend\Products\Infrastructure\Persistance\Mapping'
                prefix: 'App\Backend\Products\Domain'
                alias: Product
#            App\Backend\Common\Domain\Product:
#                is_bundle: false
#                type: xml
#                dir: '%kernel.project_dir%\src\Backend\Products\Infrastructure\Persistance\Mapping'
#                prefix: 'App\Backend\Common\Domain\Product'
#                alias: Product