networks:
  gog_shop.network:
    driver: bridge
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: gog_shop
    container_name: gog_shop
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - gog_shop.network
  nginx:
    image: nginx:1.19-alpine
    container_name: gog_shop.nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/:/etc/nginx/conf.d
    networks:
      - gog_shop.network
  db:
    image: mysql:8.0
    container_name: shop-api.db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shop-api.db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: shop-api
      MYSQL_PASSWORD: shop-api
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker-compose/mysql:/docker-compose-entrypoint-initdb.d
    networks:
      - gog_shop.network
