#index:
#    path: /
#    controller: App\Controller\DefaultController::index
product.create:
  path: /product
  controller: App\Web\Controller\ProductController::createProduct
  methods: POST
product.search:
  path: /product
  controller: App\Web\Controller\ProductController::searchProducts
  methods: GET|HEAD
product.get_product:
  path: /product/{slug}
  controller: App\Web\Controller\ProductController::getProduct
  methods: GET
  requirements:
    slug: '\d+'
product.update:
  path: /product/{slug}
  controller: App\Web\Controller\ProductController::updateProduct
  methods: PUT
  requirements:
    slug: '\d+'
product.remove:
  path: /product/{slug}
  controller: App\Web\Controller\ProductController::removeProduct
  methods: DELETE
  requirements:
    slug: '\d+'

cart.create:
  path: /cart
  controller: App\Web\Controller\CartController::createCart
  methods: POST
cart.get_cart:
  path: /cart/{slug}
  controller: App\Web\Controller\CartController::getCart
  methods: GET
  requirements:
    slug: '\d+'
cart.add_products_to_cart:
  path: /cart/{slug}/add
  controller: App\Web\Controller\CartController::addProductsToCart
  methods: PUT
  requirements:
    slug: '\d+'
cart.remove_products_from_cart:
  path: /cart/{slug}/remove
  controller: App\Web\Controller\CartController::removeProductsFromCart
  methods: PUT
  requirements:
    slug: '\d+'
